FROM golang

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    git \
    make \
    jq \
    pandoc \
    python3 \
    python3-pip \
    curl && \
    rm -rf /var/lib/apt/lists/*

RUN curl -s https://api.github.com/repos/getzola/zola/releases/latest \
    | jq -r '.assets[] | select(.name | contains("x86_64-unknown-linux-gnu.tar.gz")) | .browser_download_url' \
    | xargs curl -L -o /tmp/zola.tar.gz && \
    tar -xzf /tmp/zola.tar.gz -C /usr/local/bin/ && \
    rm /tmp/zola.tar.gz

WORKDIR /workspace
