site_name: Reddit Archive
docs_dir: data/staged
site_dir: site
theme:
  name: material
  features:
    - navigation.instant
plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_index.py