services:
  archive:
    image: golang
    container_name: archive
    working_dir: /workspace
    env_file:
      - .dev.env
    ports:
      - "8888:8000"
    volumes:
      - "..:/workspace"
      - "/mnt/d/data/reddit:/workspace/data/pushshift/reddit:rw"
    command: >
      bash -lc "
        apt-get update &&
        apt-get install -y --no-install-recommends ca-certificates git make jq pandoc python3 python3-pip &&
        pip3 install -r requirements.txt &&
        go version &&
        mkdocs --version || true &&
        exec sleep infinity
      "
